name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: windows-latest
    steps:
      - name: Set up .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SonarCloud scanner
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Verify project path
        shell: powershell
        run: |
          $projectPath = "proyecto_PDF/proyectoPDF/proyectoPDF.csproj"
          Write-Host "Checking project path: $projectPath"
          if (Test-Path $projectPath) {
              Write-Host "Project file found at: $projectPath"
          } else {
              Write-Host "Project file NOT found at: $projectPath"
              Write-Host "Available .csproj files:"
              Get-ChildItem -Recurse -Filter "*.csproj"
              exit 1
          }

      - name: Restore dependencies
        shell: powershell
        run: |
          $projectPath = "proyecto_PDF/proyectoPDF/proyectoPDF.csproj"
          dotnet restore $projectPath

      - name: Install Playwright browsers
        shell: powershell
        run: |
          $projectPath = "proyecto_PDF/proyectoPDF/proyectoPDF.csproj"
          dotnet add $projectPath package Microsoft.Playwright
          dotnet build $projectPath --configuration Release
          npx playwright install

      - name: Begin SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
          /k:"pdftest_pdftest2" `
          /o:"pdftest" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.host.url="https://sonarcloud.io" `
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" `
          /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" `
          /d:sonar.coverage.exclusions="**/*.Tests/**,**/obj/**/*,**/bin/**/*" `
          /d:sonar.test.inclusions="**/*.Tests/**" `
          /d:sonar.verbose=true `
          /d:sonar.sources="**/*" `
          /d:sonar.exclusions="**/NegocioPDF.Tests/UITests/PlaywrightUITests.cs,**/NegocioPDF.Tests/Controllers/SuscripcionControllerTests.cs"

      - name: Build solution
        shell: powershell
        run: |
          $projectPath = "proyecto_PDF/proyectoPDF/proyectoPDF.csproj"
          dotnet build $projectPath --configuration Release

      - name: Run tests with coverage (excluding DB tests)
        shell: powershell
        run: |
          $projectPath = "proyecto_PDF/proyectoPDF/proyectoPDF.csproj"
          dotnet test $projectPath `
            --configuration Release `
            --no-build `
            --filter "Category!=DatabaseTest" `
            --collect:"XPlat Code Coverage;Format=opencover" `
            --results-directory TestResults `
            --logger trx `
            --verbosity normal

      - name: End SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
