name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: windows-latest
    steps:
      - name: Set up .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SonarCloud scanner
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Begin SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
          /k:"pdftest_pdftest2" `
          /o:"pdftest" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.host.url="https://sonarcloud.io" `
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" `
          /d:sonar.sources="proyecto_PDF/NegocioPDF/**/*.cs" `
          /d:sonar.verbose=true
          /d:sonar.exclusions="**/*.Tests/**,**/obj/**/*,**/bin/**/*,**/*.html,**/*.css,**/*.js,**/bin/Debug/net8.0/.playwright/**,**/bin/Release/net8.0/.playwright/**,**/.playwright/**/*"
          

      - name: Build NegocioPDF project
        shell: powershell
        run: |
          dotnet build proyecto_PDF/NegocioPDF/NegocioPDF.csproj --configuration Release

      - name: Build NegocioPDF.Tests project
        shell: powershell
        run: |
          dotnet build proyecto_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj --configuration Release

      - name: Run tests (excluding Playwright UI Tests)
        shell: powershell
        run: |
          dotnet test proyecto_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj `
            --configuration Release `
            --no-build `
            --collect:"XPlat Code Coverage;Format=opencover" `
            --results-directory TestResults `
            --logger trx `
            --verbosity normal `
            --filter "FullyQualifiedName!~SubscriptionTests"

      - name: End SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
