name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: |
        dotnet restore proyecto_pdf/negociopdf/negociopdf.csproj
        dotnet restore proyecto_pdf/negociopdf.tests/negociopdf.tests.csproj
      
    - name: Build
      run: |
        dotnet build proyecto_pdf/negociopdf/negociopdf.csproj --no-restore
        dotnet build proyecto_pdf/negociopdf.tests/negociopdf.tests.csproj --no-restore
      
    - name: Test with coverage
      run: dotnet test proyecto_pdf/negociopdf.tests/negociopdf.tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/
      
    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: CoverageReport
        path: coveragereport
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coveragereport
        force_orphan: true

