name: Playwright UI Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Playwright Dependencies
      run: |
        npm init -y
        npm install -D @playwright/test
        npx playwright install --with-deps chromium

    - name: Create Directories
      run: |
        mkdir -p PROYECTO_PDF/NegocioPDF.Tests/videos
        mkdir -p PROYECTO_PDF/NegocioPDF.Tests/screenshots

    - name: Restore .NET dependencies
      run: |
        dotnet restore "PROYECTO_PDF/PROYECTOPDF/PROYECTOPDF.csproj"
        dotnet restore "PROYECTO_PDF/NegocioPDF/NegocioPDF.csproj"
        dotnet restore "PROYECTO_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj"

    - name: Build
      run: |
        dotnet build "PROYECTO_PDF/PROYECTOPDF/PROYECTOPDF.csproj" --no-restore
        dotnet build "PROYECTO_PDF/NegocioPDF/NegocioPDF.csproj" --no-restore
        dotnet build "PROYECTO_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj" --no-restore

    - name: Start Application
      run: |
        dotnet run --project "PROYECTO_PDF/PROYECTOPDF/PROYECTOPDF.csproj" --urls http://localhost:5260 &
        echo "Waiting for application to start..."
        sleep 15

    - name: Run UI Tests with Xvfb
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" dotnet test "PROYECTO_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj" --filter "FullyQualifiedName~UITests"

    - name: List Generated Files
      if: always()
      run: |
        echo "Contents of test directories:"
        ls -R PROYECTO_PDF/NegocioPDF.Tests/

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: |
          PROYECTO_PDF/NegocioPDF.Tests/*.png
        retention-days: 14

    - name: Upload Videos
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: videos
        path: |
          PROYECTO_PDF/NegocioPDF.Tests/videos/
        retention-days: 14

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          PROYECTO_PDF/NegocioPDF.Tests/TestResults/
        retention-days: 14

    - name: Stop Application
      if: always()
      run: killall dotnet
