name: Playwright UI Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug - List Repository Contents
      run: |
        pwd
        echo "Current directory contents:"
        ls -la
        echo "PROYECTO_PDF contents:"
        ls -la PROYECTO_PDF/

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Playwright Browsers and Dependencies
      run: |
        npm init -y
        npm install -D @playwright/test
        npx playwright install --with-deps chromium
        
    - name: Restore .NET dependencies
      run: |
        dotnet restore "PROYECTO_PDF/PROYECTOPDF/PROYECTOPDF.csproj"
        dotnet restore "PROYECTO_PDF/NegocioPDF/NegocioPDF.csproj"
        dotnet restore "PROYECTO_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj"

    - name: Build
      run: |
        dotnet build "PROYECTO_PDF/PROYECTOPDF/PROYECTOPDF.csproj" --no-restore
        dotnet build "PROYECTO_PDF/NegocioPDF/NegocioPDF.csproj" --no-restore
        dotnet build "PROYECTO_PDF/NegocioPDF.Tests/NegocioPDF.Tests.csproj" --no-restore

    - name: Start Application
      run: |
        dotnet run --project "PROYECTO_PDF/PROYECTOPDF/PROYECTOPDF.csproj" --urls http://localhost:5260 &
        echo "Waiting for application to start..."
        sleep 15

    - name: Run UI Tests
      run: |
        cd PROYECTO_PDF/NegocioPDF.Tests
        dotnet test --filter "FullyQualifiedName~UITests"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          PROYECTO_PDF/NegocioPDF.Tests/videos/
          PROYECTO_PDF/NegocioPDF.Tests/*.png
          PROYECTO_PDF/NegocioPDF.Tests/TestResults/
        retention-days: 14

    - name: Stop Application
      if: always()
      run: killall dotnet
