name: Mutation Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  mutation-testing:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker
        
    - name: Restore dependencies
      run: |
        cd PROYECTO_PDF
        dotnet restore
        
    - name: Build
      run: |
        cd PROYECTO_PDF
        dotnet build --no-restore
        
    - name: Run mutation tests
      run: |
        cd PROYECTO_PDF/NegocioPDF.Tests
        dotnet stryker
        
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Move reports to GitHub Pages directory
      run: |
        mkdir -p ./public
        cp -r PROYECTO_PDF/NegocioPDF.Tests/StrykerOutput/*/* ./public/
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Check mutation score
      run: |
        cd PROYECTO_PDF/NegocioPDF.Tests
        MUTATION_SCORE=$(jq '.mutationScore' StrykerOutput/*/reports/mutation-report.json)
        echo "Mutation score: $MUTATION_SCORE"
        if (( $(echo "$MUTATION_SCORE < 80" | bc -l) )); then
          echo "Mutation score is below 80%"
          exit 1
        fi
