name: Security Analysis

env:
  DOTNET_VERSION: '8.x'

on: push

permissions:
  contents: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Semgrep Analysis
      - name: Set up Semgrep
        run: docker pull semgrep/semgrep

      - name: Run Semgrep
        run: docker run --rm -v "${PWD}:/src" semgrep/semgrep --metrics=off --config="p/default" --json --output=semgrep.json /src/Proyecto_PDF

      - name: Install prospector-html
        run: python -m pip install prospector2html

      - name: Convert Semgrep results to HTML
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      # Snyk Analysis
      - uses: snyk/actions/setup@master

      - name: Set up .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Run Snyk test
        run: |
          cd Proyecto_PDF
          snyk code test --json | snyk-to-html -o ../snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Publish to GitHub Pages
      - name: Move reports to public folder
        run: |
          mkdir -p public/reports
          mv semgrep-report.html public/reports/
          mv snyk-report.html public/reports/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
