name: NegocioPDF Coverage Analysis
on:
  push:
    branches:
      - main
    paths:
      - 'NegocioPDF/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'NegocioPDF/**'

jobs:
  build:
    name: Analyze NegocioPDF Models
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Install SonarCloud scanner
        shell: powershell
        run: |
          dotnet tool install --global dotnet-sonarscanner
          
      - name: Build and analyze NegocioPDF Models
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet sonarscanner begin /k:"pdftest_pdftest" /o:"pdftest" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="**/Program.cs,**/Startup.cs,PROYECTOPDF/**/*,**/Controllers/**/*,**/Repositories/**/*" /d:sonar.sources="NegocioPDF/Models/Usuario.cs,NegocioPDF/Models/OperacionPDF.cs,NegocioPDF/Models/DetalleSuscripcion.cs"
          dotnet build NegocioPDF/NegocioPDF.csproj
          dotnet test NegocioPDF.Tests/NegocioPDF.Tests.csproj --no-build --collect:"XPlat Code Coverage;Format=opencover"
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
